# Generated by Django 4.0.3 on 2022-04-07 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trustfund', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trustfund',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trustfund', to=settings.AUTH_USER_MODEL),
        ),
    ]
