# Generated by Django 4.0.3 on 2022-03-31 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trustfund', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=15)),
                ('poster', models.ImageField(upload_to='posters/%Y/%m/%d/')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('trustfund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charities', to='trustfund.trustfund')),
            ],
        ),
    ]
